### ISSUE TITLE
outgoing links 

### ISSUE THREAD

**Issue by ZeynepP** [MELALab/nela-gt#5]
Great dataset, thanks for your work. I wonder if you can also provide outgoing links in the articles?It would be also interesting to see tweets that link those news besides the embedded ones in the articles. 

Bests
ZP

**Comment by mgruppi** [comment]
Hello! Thanks for your comment about these very interesting features. Here are some comments on both parts.

1. While it would be very valuable to have the tweets that link to the news articles, it is also a very challenging task because it requires a ton of Twitter-sided scraping. Especially difficult now with the free Twitter API access being discontinued - [see official Twitter post](https://twitter.com/TwitterDev/status/1621026986784337922?lang=en)

2. As for outgoing links, that is possible in our data. One can parse the `content` fields to find outgoing URLs, for instance, using regular expressions. Note that only outgoing links that are present in the body text or headline of the article will be available. This means that website navbars and footer links will not be available. One can also use the provided article URLs to scrape the raw HTML and find those links.

I hope this clarifies some your questions!

Best
