### ISSUE TITLE
Labels - NELA-GT-2020

### ISSUE THREAD

**Issue by aalexandrasilva** [MELALab/nela-gt#7]
Hello,

I'm currently working with the news data from NELA-GT-2020. I'm using the labels.csv file to assign labels to the articles. However, I've encountered an issue where I can't perfectly match the sources' scores with the sources mentioned in the articles. To clarify, there are 519 sources in the dataset, but the labels.csv file, which can be found [here](https://dataverse.harvard.edu/file.xhtml?fileId=4366864&version=2.0), only contains 336 sources.

My question is, should I consider the missing sources as unlabeled?

Additionally, I've noticed that there are sources without labels that seem very similar to others that are labeled. For instance, there are sources without labels like "chicagosun-times" and "thehuffingtonpost," while there are labeled sources like "chicagosuntimes" and "huffingtonpost."

I would like to express my gratitude in advance for any help you can provide regarding this issue.
Alexandra Silva

**Comment by mgruppi** [comment]
Hi Alexandra,

Unfortunately we do not have labels for every source in the dataset, those that are not present in the `labels.csv` file should be treated as unlabeled sources.

As for your second question, yes, there is some inconsistency regarding the naming of sources. We have been working to try and keep it as consistent as possible b

ut, because we deal with data that originates from many different places, sometimes we miss some of them and they end up with slightly different names. With that said, you safely consider "chicagosun-times" the same as "chicagosuntimes" and "thehugginftonpost" as "huffingtonpost".

I am attaching a list of known source typos we have found over time, which you can use to correct that issue. Hope this helps: [source_typos.csv](https://github.com/MELALab/nela-gt/files/12930437/source_typos.csv)


Let me know if you have any further questions.

Best,
Mauricio

**Comment by aalexandrasilva** [comment]
That is really helpful indeed, thanks! 😁
